# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget crengine-ng::crengine-ng_static crengine-ng::cre_chmlib crengine-ng::cre_antiword crengine-ng::cre_qimagescale crengine-ng::cre_rfc6234-shas crengine-ng::cre_md4c-html)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target crengine-ng::crengine-ng_static
add_library(crengine-ng::crengine-ng_static STATIC IMPORTED)

set_target_properties(crengine-ng::crengine-ng_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "LINUX=1;_LINUX=1;LVLONG_FILE_SUPPORT=1;CR_EMULATE_GETTEXT=1"
  INTERFACE_LINK_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../../../lib"
  INTERFACE_LINK_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/../../../lib/libz.so;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libpng.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libz.so;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libjpeg.a;\$<LINK_ONLY:cpufeatures-webp>;\$<LINK_ONLY:webpdecoder>;\$<LINK_ONLY:webp>;\$<LINK_ONLY:webpdemux>;\$<LINK_ONLY:webpmux>;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libfreetype.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libharfbuzz.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libfribidi.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libunibreak.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libzstd.a;${CMAKE_CURRENT_LIST_DIR}/../../../lib/libutf8proc.a;\$<LINK_ONLY:crengine-ng::cre_chmlib>;\$<LINK_ONLY:crengine-ng::cre_antiword>;\$<LINK_ONLY:crengine-ng::cre_qimagescale>;\$<LINK_ONLY:crengine-ng::cre_rfc6234-shas>;\$<LINK_ONLY:crengine-ng::cre_md4c-html>"
)

# Create imported target crengine-ng::cre_chmlib
add_library(crengine-ng::cre_chmlib INTERFACE IMPORTED)

# Create imported target crengine-ng::cre_antiword
add_library(crengine-ng::cre_antiword INTERFACE IMPORTED)

# Create imported target crengine-ng::cre_qimagescale
add_library(crengine-ng::cre_qimagescale INTERFACE IMPORTED)

# Create imported target crengine-ng::cre_rfc6234-shas
add_library(crengine-ng::cre_rfc6234-shas INTERFACE IMPORTED)

# Create imported target crengine-ng::cre_md4c-html
add_library(crengine-ng::cre_md4c-html INTERFACE IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/crengine-ng-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
