// Genau die im App-UI verwendeten Glyphen (kebab-SVG-Name → Kotlin-Property).
// Erweitern: hier ergänzen, dann `npm run generate`. Siehe README.md.
export const ICONS = {
  "align-justify": "AlignJustify",
  "align-left": "AlignLeft",
  "arrow-left": "ArrowLeft",
  "arrow-right": "ArrowRight",
  "book-open": "BookOpen",
  "bookmark": "Bookmark",
  "check": "Check",
  "chevron-down": "ChevronDown",
  "chevron-right": "ChevronRight",
  "chevron-up": "ChevronUp",
  "circle-stop": "CircleStop",
  "cloud": "Cloud",
  "cloud-download": "CloudDownload",
  "contrast": "Contrast",
  "download": "Download",
  "ellipsis-vertical": "EllipsisVertical",
  "gallery-vertical": "GalleryVertical",
  "grid-2x2": "Grid2x2",
  "hard-drive-download": "HardDriveDownload",
  "info": "Info",
  "languages": "Languages",
  "layout-dashboard": "LayoutDashboard",
  "layout-grid": "LayoutGrid",
  "library": "Library",
  "list": "List",
  "list-filter": "ListFilter",
  "minus": "Minus",
  "palette": "Palette",
  "plus": "Plus",
  "puzzle": "Puzzle",
  "refresh-cw": "RefreshCw",
  "search": "Search",
  "server": "Server",
  "settings": "Settings",
  "square-pen": "SquarePen",
  "trash-2": "Trash2",
  "type": "Type",
  "x": "X",
};
